name: Build

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{vars.NODE_VERSION}}
      - run: npm ci
      - run: next build
