/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch a paginated list of posts, ordered by the time of their creation. May contain deleted posts. */
        get: operations["PostsController_list"];
        put?: never;
        /** @description Create a new post with the logged in user. A post can contain an optional image and must contain text. */
        post: operations["PostsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a specific post. */
        get: operations["PostsController_single"];
        put?: never;
        /** @description Create a reply to a post with the logged in user. A reply can contain an optional image and must contain text. */
        post: operations["PostsController_reply"];
        /** @description Deletes a post or reply if it exists and if the logged in user is the author. */
        delete: operations["PostsController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an ordered list of replies for the given post. */
        get: operations["PostsController_replies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Search for posts or replies in the database. The result is always paginated and ordered by the time of their creation. */
        post: operations["PostsController_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Create a like on a specific post. */
        put: operations["LikesController_like"];
        post?: never;
        /** @description Delete a like on a specific post. */
        delete: operations["LikesController_unlike"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch a paginated list of users, ordered by their username. */
        get: operations["UsersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch your own authenticated profile. */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch a user by id. */
        get: operations["UsersController_getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PostsController_list: {
        parameters: {
            query?: {
                /** @description The offset for pagination of further calls. Defaults to 0 if omitted. */
                offset?: number;
                /** @description The amount of posts that is returned in one call. Minimum is 1, maximum is 1000. Defaults to 100. */
                limit?: number;
                /** @description The ID of a post, to only return posts that are newer than the given post. If omitted, all posts are returned. */
                newerThan?: string;
                /** @description The ID of a post, to only return posts that are older than the given post. If omitted, all posts are returned. */
                olderThan?: string;
                /** @description The ID of a creator. Only posts of the given creator should be returned. If omitted, all posts are returned. */
                creator?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The paginated list of posts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "count": 100,
                     *       "data": [
                     *         {
                     *           "id": "1",
                     *           "creator": "a",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "2",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "3",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "4",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "5",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "12",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "13",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "14",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "15",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "21",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "22",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "23",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "24",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "25",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "26",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "27",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "28",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "29",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "210",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "211",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "212",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "213",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "214",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "112",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "13121",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "411",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "124122",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "512351v",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "asdfgasdf",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "safas",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "etrrtv",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "qbrtnw",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "wrunwze",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "wnrtzwrt",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "wrtznwr",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         },
                     *         {
                     *           "id": "wrtznwrt",
                     *           "creator": "b",
                     *           "text": "Hello World! @user #newpost",
                     *           "likeCount": 45,
                     *           "likedByUser": false,
                     *           "replyCount": 12
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        data?: {
                            /**
                             * Format: ulid
                             * @description ID of the post, defined in the ULID format.
                             * @example 01GDMMR85BEHP8AKV8ZGGM259K
                             */
                            id?: string;
                            /**
                             * @description ID of the user who created the post.
                             * @example 179944860378202369
                             */
                            creator?: string;
                            /**
                             * @description Text in the post.
                             * @example Hello World! @user #newpost
                             */
                            text?: string;
                            /**
                             * @description URL - if any - to the media object attached to this post.
                             * @example https://storage.googleapis.com/cas-fee-adv-qwacker-api-local-dev/1094b5e0-5f30-4f0b-a342-ae12936c42ff
                             */
                            mediaUrl?: string | null;
                            /**
                             * @description If mediaUrl is set, this field contains the mime type of the media object.
                             * @example image/png
                             */
                            mediaType?: string | null;
                            /**
                             * @description Number of total likes on this post.
                             * @example 42
                             */
                            likeCount?: number;
                            /**
                             * @description Indicates if the current user liked this post. If the call was made unauthorized, all posts are returned with this field set to false.
                             * @example true
                             */
                            likedByUser?: boolean;
                            /**
                             * @description Indicates, that this result is a post.
                             * @example post
                             */
                            type?: Record<string, never>;
                            /**
                             * @description Number of total replies to this post.
                             * @example 42
                             */
                            replyCount?: number;
                        }[];
                        /**
                         * @description The total count of posts in the system.
                         * @example 1000
                         */
                        count?: number;
                        /**
                         * @description If filled, hints the next api call to make to fetch the next page.
                         * @example /posts?offset=100&limit=100
                         */
                        next?: string | null;
                        /**
                         * @description If filled, hints the next api call to make to fetch the previous page.
                         * @example /posts?offset=0&limit=100
                         */
                        previous?: string | null;
                    };
                };
            };
        };
    };
    PostsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The data for the post to create. */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * @description The text of the post.
                     * @example Hello World!
                     */
                    text?: string;
                    /** @description The image of the post. */
                    image?: Record<string, never> | null;
                };
            };
        };
        responses: {
            /** @description The post was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: ulid
                         * @description ID of the post, defined in the ULID format.
                         * @example 01GDMMR85BEHP8AKV8ZGGM259K
                         */
                        id?: string;
                        /**
                         * @description ID of the user who created the post.
                         * @example 179944860378202369
                         */
                        creator?: string;
                        /**
                         * @description Text in the post.
                         * @example Hello World! @user #newpost
                         */
                        text?: string;
                        /**
                         * @description URL - if any - to the media object attached to this post.
                         * @example https://storage.googleapis.com/cas-fee-adv-qwacker-api-local-dev/1094b5e0-5f30-4f0b-a342-ae12936c42ff
                         */
                        mediaUrl?: string | null;
                        /**
                         * @description If mediaUrl is set, this field contains the mime type of the media object.
                         * @example image/png
                         */
                        mediaType?: string | null;
                        /**
                         * @description Number of total likes on this post.
                         * @example 42
                         */
                        likeCount?: number;
                        /**
                         * @description Indicates if the current user liked this post. If the call was made unauthorized, all posts are returned with this field set to false.
                         * @example true
                         */
                        likedByUser?: boolean;
                        /**
                         * @description Indicates, that this result is a post.
                         * @example post
                         */
                        type?: Record<string, never>;
                        /**
                         * @description Number of total replies to this post.
                         * @example 42
                         */
                        replyCount?: number;
                    };
                };
            };
            /** @description The uploaded file is not an image or bigger than 5MB. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No authenticated user is found. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_single: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID (ulid) of the post to get.
                 * @example 01GEESHPQQ4NJKNZJN9AKWQW6G
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested post. This may be a post, a reply, or a deleted post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: ulid
                         * @description ID of the post, defined in the ULID format.
                         * @example 01GDMMR85BEHP8AKV8ZGGM259K
                         */
                        id?: string;
                        /**
                         * @description ID of the user who created the post.
                         * @example 179944860378202369
                         */
                        creator?: string;
                        /**
                         * @description Text in the post.
                         * @example Hello World! @user #newpost
                         */
                        text?: string;
                        /**
                         * @description URL - if any - to the media object attached to this post.
                         * @example https://storage.googleapis.com/cas-fee-adv-qwacker-api-local-dev/1094b5e0-5f30-4f0b-a342-ae12936c42ff
                         */
                        mediaUrl?: string | null;
                        /**
                         * @description If mediaUrl is set, this field contains the mime type of the media object.
                         * @example image/png
                         */
                        mediaType?: string | null;
                        /**
                         * @description Number of total likes on this post.
                         * @example 42
                         */
                        likeCount?: number;
                        /**
                         * @description Indicates if the current user liked this post. If the call was made unauthorized, all posts are returned with this field set to false.
                         * @example true
                         */
                        likedByUser?: boolean;
                        /**
                         * @description Indicates, that this result is a post.
                         * @example post
                         */
                        type?: Record<string, never>;
                        /**
                         * @description Number of total replies to this post.
                         * @example 42
                         */
                        replyCount?: number;
                    } | {
                        /**
                         * Format: ulid
                         * @description ID of the post, defined in the ULID format.
                         * @example 01GDMMR85BEHP8AKV8ZGGM259K
                         */
                        id?: string;
                        /**
                         * @description ID of the user who created the post.
                         * @example 179944860378202369
                         */
                        creator?: string;
                        /**
                         * @description Text in the post.
                         * @example Hello World! @user #newpost
                         */
                        text?: string;
                        /**
                         * @description URL - if any - to the media object attached to this post.
                         * @example https://storage.googleapis.com/cas-fee-adv-qwacker-api-local-dev/1094b5e0-5f30-4f0b-a342-ae12936c42ff
                         */
                        mediaUrl?: string | null;
                        /**
                         * @description If mediaUrl is set, this field contains the mime type of the media object.
                         * @example image/png
                         */
                        mediaType?: string | null;
                        /**
                         * @description Number of total likes on this post.
                         * @example 42
                         */
                        likeCount?: number;
                        /**
                         * @description Indicates if the current user liked this post. If the call was made unauthorized, all posts are returned with this field set to false.
                         * @example true
                         */
                        likedByUser?: boolean;
                        /**
                         * @description Indicates, that this result is a reply to a post.
                         * @example reply
                         */
                        type?: Record<string, never>;
                        /**
                         * Format: ulid
                         * @description Reference ID to the parent post.
                         * @example 01GDMMR85BEHP8AKV8ZGGM259K
                         */
                        parentId?: string;
                    } | {
                        /**
                         * @description Indicates, that this result is a deleted post.
                         * @example deleted
                         */
                        type?: Record<string, never>;
                        /**
                         * Format: ulid
                         * @description ID of the post, defined in the ULID format.
                         * @example 01GDMMR85BEHP8AKV8ZGGM259K
                         */
                        id?: string;
                        /**
                         * @description ID of the user who created the post.
                         * @example 179944860378202369
                         */
                        creator?: string;
                        /**
                         * @description ID of the parent.
                         * @example 01GDMMR85BEHP8AKV8ZGGM259K
                         */
                        parentId?: string | null;
                    };
                };
            };
        };
    };
    PostsController_reply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID (ulid) of the post to reply to.
                 * @example 01F1ZQZQXZJZJXZQZQZQZQZQZQ
                 */
                id: string;
            };
            cookie?: never;
        };
        /** @description The data for the reply to create. */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * @description The text of the reply.
                     * @example Hello World!
                     */
                    text?: string;
                    /** @description The image of the reply. */
                    image?: Record<string, never> | null;
                };
            };
        };
        responses: {
            /** @description The reply was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: ulid
                         * @description ID of the post, defined in the ULID format.
                         * @example 01GDMMR85BEHP8AKV8ZGGM259K
                         */
                        id?: string;
                        /**
                         * @description ID of the user who created the post.
                         * @example 179944860378202369
                         */
                        creator?: string;
                        /**
                         * @description Text in the post.
                         * @example Hello World! @user #newpost
                         */
                        text?: string;
                        /**
                         * @description URL - if any - to the media object attached to this post.
                         * @example https://storage.googleapis.com/cas-fee-adv-qwacker-api-local-dev/1094b5e0-5f30-4f0b-a342-ae12936c42ff
                         */
                        mediaUrl?: string | null;
                        /**
                         * @description If mediaUrl is set, this field contains the mime type of the media object.
                         * @example image/png
                         */
                        mediaType?: string | null;
                        /**
                         * @description Number of total likes on this post.
                         * @example 42
                         */
                        likeCount?: number;
                        /**
                         * @description Indicates if the current user liked this post. If the call was made unauthorized, all posts are returned with this field set to false.
                         * @example true
                         */
                        likedByUser?: boolean;
                        /**
                         * @description Indicates, that this result is a post.
                         * @example post
                         */
                        type?: Record<string, never>;
                        /**
                         * @description Number of total replies to this post.
                         * @example 42
                         */
                        replyCount?: number;
                    };
                };
            };
            /** @description The uploaded file is not an image or bigger than 5MB. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No authenticated user is found. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No post with the given ID was found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID (ulid) of the post that shall be deleted. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The post was deleted if it existed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No authenticated user is found. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_replies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The ID (ulid) of the post to get the replies from.
                 * @example 01GEESHPQQ4NJKNZJN9AKWQW6G
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list of replies for a given post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: ulid
                         * @description ID of the post, defined in the ULID format.
                         * @example 01GDMMR85BEHP8AKV8ZGGM259K
                         */
                        id?: string;
                        /**
                         * @description ID of the user who created the post.
                         * @example 179944860378202369
                         */
                        creator?: string;
                        /**
                         * @description Text in the post.
                         * @example Hello World! @user #newpost
                         */
                        text?: string;
                        /**
                         * @description URL - if any - to the media object attached to this post.
                         * @example https://storage.googleapis.com/cas-fee-adv-qwacker-api-local-dev/1094b5e0-5f30-4f0b-a342-ae12936c42ff
                         */
                        mediaUrl?: string | null;
                        /**
                         * @description If mediaUrl is set, this field contains the mime type of the media object.
                         * @example image/png
                         */
                        mediaType?: string | null;
                        /**
                         * @description Number of total likes on this post.
                         * @example 42
                         */
                        likeCount?: number;
                        /**
                         * @description Indicates if the current user liked this post. If the call was made unauthorized, all posts are returned with this field set to false.
                         * @example true
                         */
                        likedByUser?: boolean;
                        /**
                         * @description Indicates, that this result is a reply to a post.
                         * @example reply
                         */
                        type?: Record<string, never>;
                        /**
                         * Format: ulid
                         * @description Reference ID to the parent post.
                         * @example 01GDMMR85BEHP8AKV8ZGGM259K
                         */
                        parentId?: string;
                    }[];
                };
            };
        };
    };
    PostsController_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The search parameters. */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Search for posts that contain this text.
                     * @example Hello World
                     */
                    text?: string | null;
                    tags?: string[];
                    likedBy?: string[];
                    mentions?: string[];
                    /**
                     * @description Search for posts that are replies to other posts. If omitted, all posts are searched.
                     * @example false
                     */
                    isReply?: boolean | null;
                    /**
                     * @description The offset for pagination of further calls.
                     * @default 0
                     * @example 0
                     */
                    offset?: number | null;
                    /**
                     * @description The amount of posts that is returned in one call. Minimum is 1, maximum is 1000.
                     * @default 100
                     * @example 500
                     */
                    limit?: number | null;
                };
            };
        };
        responses: {
            /** @description The paginated search result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: ({
                            /**
                             * Format: ulid
                             * @description ID of the post, defined in the ULID format.
                             * @example 01GDMMR85BEHP8AKV8ZGGM259K
                             */
                            id?: string;
                            /**
                             * @description ID of the user who created the post.
                             * @example 179944860378202369
                             */
                            creator?: string;
                            /**
                             * @description Text in the post.
                             * @example Hello World! @user #newpost
                             */
                            text?: string;
                            /**
                             * @description URL - if any - to the media object attached to this post.
                             * @example https://storage.googleapis.com/cas-fee-adv-qwacker-api-local-dev/1094b5e0-5f30-4f0b-a342-ae12936c42ff
                             */
                            mediaUrl?: string | null;
                            /**
                             * @description If mediaUrl is set, this field contains the mime type of the media object.
                             * @example image/png
                             */
                            mediaType?: string | null;
                            /**
                             * @description Number of total likes on this post.
                             * @example 42
                             */
                            likeCount?: number;
                            /**
                             * @description Indicates if the current user liked this post. If the call was made unauthorized, all posts are returned with this field set to false.
                             * @example true
                             */
                            likedByUser?: boolean;
                            /**
                             * @description Indicates, that this result is a post.
                             * @example post
                             */
                            type?: Record<string, never>;
                            /**
                             * @description Number of total replies to this post.
                             * @example 42
                             */
                            replyCount?: number;
                        } | {
                            /**
                             * Format: ulid
                             * @description ID of the post, defined in the ULID format.
                             * @example 01GDMMR85BEHP8AKV8ZGGM259K
                             */
                            id?: string;
                            /**
                             * @description ID of the user who created the post.
                             * @example 179944860378202369
                             */
                            creator?: string;
                            /**
                             * @description Text in the post.
                             * @example Hello World! @user #newpost
                             */
                            text?: string;
                            /**
                             * @description URL - if any - to the media object attached to this post.
                             * @example https://storage.googleapis.com/cas-fee-adv-qwacker-api-local-dev/1094b5e0-5f30-4f0b-a342-ae12936c42ff
                             */
                            mediaUrl?: string | null;
                            /**
                             * @description If mediaUrl is set, this field contains the mime type of the media object.
                             * @example image/png
                             */
                            mediaType?: string | null;
                            /**
                             * @description Number of total likes on this post.
                             * @example 42
                             */
                            likeCount?: number;
                            /**
                             * @description Indicates if the current user liked this post. If the call was made unauthorized, all posts are returned with this field set to false.
                             * @example true
                             */
                            likedByUser?: boolean;
                            /**
                             * @description Indicates, that this result is a reply to a post.
                             * @example reply
                             */
                            type?: Record<string, never>;
                            /**
                             * Format: ulid
                             * @description Reference ID to the parent post.
                             * @example 01GDMMR85BEHP8AKV8ZGGM259K
                             */
                            parentId?: string;
                        })[];
                        /**
                         * @description The total count of posts in the executed search.
                         * @example 1000
                         */
                        count?: number;
                        /** @description If filled, hints the search parameters for the next page. */
                        next?: {
                            /**
                             * @description Search for posts that contain this text.
                             * @example Hello World
                             */
                            text?: string | null;
                            tags?: string[];
                            likedBy?: string[];
                            mentions?: string[];
                            /**
                             * @description Search for posts that are replies to other posts. If omitted, all posts are searched.
                             * @example false
                             */
                            isReply?: boolean | null;
                            /**
                             * @description The offset for pagination of further calls.
                             * @default 0
                             * @example 0
                             */
                            offset: number | null;
                            /**
                             * @description The amount of posts that is returned in one call. Minimum is 1, maximum is 1000.
                             * @default 100
                             * @example 500
                             */
                            limit: number | null;
                        } | null;
                        /** @description If filled, hints the search parameters for the previous page. */
                        previous?: {
                            /**
                             * @description Search for posts that contain this text.
                             * @example Hello World
                             */
                            text?: string | null;
                            tags?: string[];
                            likedBy?: string[];
                            mentions?: string[];
                            /**
                             * @description Search for posts that are replies to other posts. If omitted, all posts are searched.
                             * @example false
                             */
                            isReply?: boolean | null;
                            /**
                             * @description The offset for pagination of further calls.
                             * @default 0
                             * @example 0
                             */
                            offset: number | null;
                            /**
                             * @description The amount of posts that is returned in one call. Minimum is 1, maximum is 1000.
                             * @default 100
                             * @example 500
                             */
                            limit: number | null;
                        } | null;
                    };
                };
            };
        };
    };
    LikesController_like: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID (ulid) of the post to like. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The like was created. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No authenticated user is found. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LikesController_unlike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID (ulid) of the post to unlike. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The like was deleted. This is also returned when no specific userId/postId like was found. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No authenticated user is found. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_list: {
        parameters: {
            query?: {
                /** @description The offset for pagination of further calls. Defaults to 0 if omitted. */
                offset?: number;
                /** @description The amount of users that is returned in one call. Minimum is 1, maximum is 1000. Defaults to 100. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The paginated list of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /**
                             * @description The (long) ID of the user.
                             * @example 179828644301046017
                             */
                            id?: string;
                            /**
                             * @description The username of the user. May be used to mention someone in the posts.
                             * @example johnDoe
                             */
                            userName?: string;
                            /**
                             * @description The first name of the user.
                             * @example John
                             */
                            firstName?: string;
                            /**
                             * @description The last name of the user.
                             * @example Doe
                             */
                            lastName?: string;
                            /**
                             * @description URL to the avatar of the user. This field may be empty (empty string).
                             * @example avatar.png
                             */
                            avatarUrl?: string;
                        }[];
                        /**
                         * @description The total count of users in the system.
                         * @example 1000
                         */
                        count?: number;
                        /**
                         * @description If filled, hints the next api call to make to fetch the next page.
                         * @example /users?offset=100&limit=100
                         */
                        next?: string | null;
                        /**
                         * @description If filled, hints the next api call to make to fetch the previous page.
                         * @example /users?offset=0&limit=100
                         */
                        previous?: string | null;
                    };
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Your own profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description The (long) ID of the user.
                         * @example 179828644301046017
                         */
                        id?: string;
                        /**
                         * @description The username of the user. May be used to mention someone in the posts.
                         * @example johnDoe
                         */
                        userName?: string;
                        /**
                         * @description The first name of the user.
                         * @example John
                         */
                        firstName?: string;
                        /**
                         * @description The last name of the user.
                         * @example Doe
                         */
                        lastName?: string;
                        /**
                         * @description URL to the avatar of the user. This field may be empty (empty string).
                         * @example avatar.png
                         */
                        avatarUrl?: string;
                    };
                };
            };
        };
    };
    UsersController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description The (long) ID of the user.
                         * @example 179828644301046017
                         */
                        id?: string;
                        /**
                         * @description The username of the user. May be used to mention someone in the posts.
                         * @example johnDoe
                         */
                        userName?: string;
                        /**
                         * @description The first name of the user.
                         * @example John
                         */
                        firstName?: string;
                        /**
                         * @description The last name of the user.
                         * @example Doe
                         */
                        lastName?: string;
                        /**
                         * @description URL to the avatar of the user. This field may be empty (empty string).
                         * @example avatar.png
                         */
                        avatarUrl?: string;
                    };
                };
            };
        };
    };
}
